//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Project.rc
//
#define IDC_MYICON                      2
#define IDC_SAVE                        3
#define IDC_ACCEPT                      3
#define IDC_ADD                         4
#define IDC_ACCEPT_DBF                  4
#define IDC_INS                         5
#define IDC_ADD_DBF                     5
#define IDC_DEL                         6
#define IDC_INS_DBF                     6
#define IDC_READ                        7
#define IDC_DEL_DBF                     7
#define IDC_WRITE                       8
#define IDC_ACCEPT_DBS                  8
#define IDC_ADD_DBS                     9
#define IDC_PARAM_FREQ_CORR_PEAKS       9
#define IDC_INS_DBS                     10
#define IDC_PARAM_FREQ_CORR_SPECTR      10
#define IDC_DEL_DBS                     11
#define IDC_BROWSE                      12
#define IDC_BLOCK_TIME                  13
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_PROG                        108
#define ID_MENU_MAIN                    109
#define IDA_MAIN                        109
#define IDS_Err_CanNotOpen              110
#define IDS_Err_WrongFormatWAV          111
#define IDS_Err_ReadFile                112
#define IDS_Err_CanNotSave              113
#define IDS_Err_WriteFile               114
#define IDS_Mess_LargeTimeWin           115
#define IDS_Mess_LargeFreqArr           116
#define IDS_Mess_LargeTimeArr           117
#define IDS_Mess_FileNotOpen            118
#define IDS_Mess_CanNotExit             119
#define IDS_Quest_FileExists            120
#define IDS_Err_LongFilePathName        121
#define IDS_Err_WrongExtFile            122
#define IDS_Err_AmbigChoiceExt          124
#define IDS_Mess_WarningWrongExt        125
#define IDS_Filt_Sound                  126
#define IDS_HeaderDlg_OpenWav           127
#define IDS_HeaderDlg_OpenDBF           128
#define IDS_Filt_DBS_Files              129
#define IDD_PAR_PROC_SPECTR             129
#define IDD_CNTRL_MAIN                  130
#define IDS_FunAct_Sigmoid              130
#define IDD_DATABASE                    131
#define IDS_FunAct_SigmBiPolar          131
#define IDD_PAR_PEAKS                   132
#define IDS_FunAct_HypTang              132
#define IDD_PAR_NNW                     133
#define IDS_Mess_NoSampTrainNNW         133
#define IDBI_FILE_OPEN                  134
#define IDD_PAR_TRAIN_NNW               134
#define IDS_Filt_ParNNW_Vowel           134
#define IDBI_AMP_NORM                   135
#define IDS_HeaderDlg_OpenParNNW        135
#define IDBI_SPECTR                     136
#define IDS_HeaderDlg_SaveParNNW        136
#define IDBI_SIGNAL                     137
#define IDS_Err_DLLProg                 137
#define IDS_Err_NoFileDLL               138
#define IDBI_PROC                       139
#define IDS_Err_LoadDLL                 139
#define IDBI_PLAY_SOUND                 140
#define IDS_HeaderAlphaConst            140
#define IDBI_CAPT_SOUND                 141
#define IDS_HeaderAlphaAdapt            141
#define IDBI_TIME                       142
#define IDS_Err_NoMemBitmap             142
#define IDBIS_ACCEPT                    143
#define IDS_Filt_ParNNW_Cons            143
#define IDBI_ADJUST                     144
#define IDS_Filt_NNW_Vowel              144
#define IDBI_DBS_NNW                    145
#define IDS_Filt_NNW_Cons               145
#define IDBI_DELETE                     146
#define IDS_HeaderDlg_OpenNNW           146
#define IDBI_SAVE                       147
#define IDS_HeaderDlg_SaveNNW           147
#define IDBI_ACCEPT                     148
#define IDS_NewNNW                      148
#define IDS_SpectrWinName_Gauss         149
#define IDBI_INS                        150
#define IDS_SpectrWinName_CosHann       150
#define IDBI_ADD                        151
#define IDS_SpectrWinName_Hamming       151
#define IDBI_NNW_SYN                    152
#define IDS_SpectrWinName_BlackmanHarris 152
#define IDD_CNTRL_VIEW_NNW              153
#define IDS_SpectrWinName_KaizerBessel  153
#define IDBI_WATCH_NNW                  154
#define IDS_SpectrWinName_NoSmooth      154
#define IDS_Quest_NoSavedNNW            155
#define IDS_SoundsVowel                 156
#define IDI_NNW                         156
#define IDS_SoundsConsonant             157
#define IDI_TEXT                        157
#define IDS_BtnNNWWork_Work             158
#define IDBI_NNW_INP                    158
#define IDS_BtnNNWWork_Net              159
#define IDBI_SOUND_REC                  159
#define IDS_BtnNNWAxons_Amp             160
#define IDBI_WIN_TEXT                   160
#define IDS_BtnNNWAxons_Excit           161
#define IDBI_SET_TIME                   161
#define IDS_Mess_ErrConfNNW             162
#define IDBI_NNW_VIEW                   162
#define IDS_Mess_ErrLoadNNW             163
#define IDBI_NNW_STAT                   163
#define IDS_NameRecord                  164
#define IDBI_BROWSE                     164
#define IDS_HeaderDlg_SaveWav           165
#define IDS_ErrParFindPeaks             166
#define IDBI_NNW_ERR_TRAIN              166
#define IDS_Err_CanNotReadDBS           167
#define IDBI_NNW_ERR_CNTRL              167
#define IDS_Err_NoFileDBS               168
#define IDS_Err_NoFileWAV               169
#define IDS_Err_CanNotReadWAV           170
#define IDS_Btn_WinText                 171
#define IDS_Btn_WinClose                172
#define IDS_Btn_Record                  173
#define IDS_Btn_Stop                    174
#define IDS_Btn_Recogn                  175
#define IDS_Btn_Sound                   176
#define IDS_Btn_Block                   177
#define IDS_Btn_Enable                  178
#define IDS_Btn_WinViewNet              179
#define IDS_MethTrain_Sequent           180
#define IDS_MethTrain_GroupSearch       181
#define IDS_Btn_Train                   182
#define IDS_MethTrain_SeqLay            183
#define IDS_MethTrain_GroupAdapt        184
#define IDS_MethTrain_SeqRep            185
#define IDS_Btn_PreProc                 186
#define IDS_Err_NoTrainData             187
#define IDS_Filt_NNW_Spectr             188
#define IDS_SoundsSpectr                189
#define IDS_Mess_NoPreProc              190
#define IDS_Btn_SynthSound              191
#define IDS_Filt_ParNNW_Spectr          192
#define IDS_SpectrWinName_Blackman      193
#define IDS_SpectrWinName_Natall        194
#define IDS_SpectrWinName_BlNatall      195
#define IDD_ADJ_SOUND_CAPTURE           196
#define IDS_SpectrWinName_FlatTop       196
#define IDD_STAT_SOUNDS                 197
#define IDS_SpectrWinName_Barlett       197
#define IDS_SpectrWinName_BarHann       198
#define IDD_PAR_FREQ_CORR_PEAKS         198
#define IDS_SpectrWinName_Lanczos       199
#define IDD_PAR_FREQ_CORR_SPECTR        199
#define IDS_SpectrWinName_Cos           200
#define IDS_Btn_Processing              201
#define IDS_MethTrain_GroupRandMC       202
#define IDS_FunAct_Log                  203
#define IDS_FunAct_Lin                  204
#define IDS_Err_DiffParNNW              205
#define IDS_Mess_ZeroAdaptStep          206
#define IDS_MessDiff_SPS                207
#define IDS_Btn_SetData                 208
#define IDS_Mess_NoInpData              209
#define IDS_WrongIntervalsData          210
#define IDC_TIME_WIDTH                  1006
#define IDC_COORDTIME                   1007
#define IDC_COORDFREQ                   1008
#define IDC_FILE_NAME                   1009
#define IDC_PERC                        1010
#define IDC_AMPL_DIAG                   1012
#define IDC_AMPL_SIG                    1013
#define IDC_AMPL_GRSP                   1014
#define IDC_COMBO_DEVICES               1017
#define IDC_COMBO_FORMAT                1018
#define IDC_AMPLP_DIAG                  1019
#define IDC_AMPLM_DIAG                  1020
#define IDC_AMPLP_SIG                   1021
#define IDC_AMPLM_SYN                   1021
#define IDC_AMPLOK_DIAG                 1022
#define IDC_AMPLM_INP                   1022
#define IDC_COORDAMPL                   1023
#define IDC_AMPLM_SIG                   1024
#define IDC_AMPLOK_SIG                  1025
#define IDC_OPEN_FILE                   1026
#define IDC_PROCESSING                  1027
#define IDC_TIME_STEP                   1028
#define IDC_PLAY_SND                    1028
#define IDC_AMPLP_GRSP                  1029
#define IDC_STATISTICS                  1029
#define IDC_AMPLM_GRSP                  1030
#define IDC_RESULTS                     1030
#define IDC_AMPLOK_GRSP                 1031
#define IDC_PLAY_SND_PEAKS              1031
#define IDC_CAPT_SND                    1032
#define IDC_ADJ_SPECTR                  1033
#define IDC_DBS_NNW                     1034
#define IDC_METHOD                      1035
#define IDC_OPEN_DBS                    1035
#define IDC_CAPT_REC                    1036
#define IDC_WIN_TEXT                    1037
#define IDC_PROGR                       1038
#define IDM_ADJUST_PAR_SPECTR           1039
#define IDC_WIN_VIEW_NNW                1039
#define IDM_COMPUTE                     1040
#define IDM_OPEN_WAV                    1041
#define IDC_DBF                         1044
#define IDC_DBS                         1045
#define IDC_SOUND_USE                   1046
#define IDC_SOUND_TRAIN                 1047
#define IDC_FILE_USE                    1048
#define IDC_FILE_TRAIN                  1049
#define IDC_TRAINING                    1050
#define IDC_ERR_TRAIN                   1051
#define IDC_ERR_CONTR                   1052
#define IDC_COE_SMALL_PEAKS             1052
#define IDC_ADJUST_NNW                  1053
#define IDC_FREQ_MIN                    1054
#define IDC_ADJUST_TRAIN                1054
#define IDC_FREQ_MAX                    1055
#define IDC_NUM_CYCLE                   1055
#define IDC_ERR_FREQ                    1056
#define IDC_NAME_NNW_VOWEL              1056
#define IDC_WID_PEAKS                   1057
#define IDC_NAME_NNW_CONSONANT          1057
#define IDC_LEV_POW_PEAKS               1058
#define IDC_PROC_SPECTR_PEAKS           1058
#define IDC_CORRECT_FREQ                1059
#define IDC_CHECK_ALL_DATA              1059
#define IDC_AMP_CORR_FREQ               1060
#define IDC_FUN_ACT                     1060
#define IDC_CHECK_ALL_RES               1060
#define IDC_NUM_NEURONS                 1061
#define IDC_CHECK_SYNTH_CORR            1061
#define IDC_LIST_LAYERS                 1062
#define IDC_AMP_THRESHOLD               1062
#define IDC_NAME_NNW_SPECTR             1062
#define IDC_NUM_INI                     1063
#define IDC_SET_INP_DATA                1063
#define IDC_NUM_FIN                     1064
#define IDC_NAME_NNW_COHONEN            1064
#define IDC_COE_RECOGN_PEAK             1065
#define IDC_FR_CORR_DB                  1065
#define IDC_RADIO_VOWEL                 1066
#define IDC_RADIO_CONS                  1067
#define IDC_NUM_STEPS_RAND              1068
#define IDC_RADIO_SPECTR                1068
#define IDC_NUM_STEPS_TRAIN             1069
#define IDC_RADIO_COHONEN               1069
#define IDC_STEP_TRAIN                  1070
#define IDC_NUM_RAND_SEQ                1071
#define IDC_ADAPT_STEP_MIN              1071
#define IDC_ADAPTIVE_STEP               1072
#define IDC_NAME_FILE_DBF               1072
#define IDC_APPLY                       1073
#define IDC_ASTEP_MAX                   1073
#define IDC_HEADER_ALPHA                1074
#define IDC_ASTEP_MIN                   1074
#define IDC_NAME_PERSON                 1075
#define IDC_RAND_SAMPLES                1075
#define IDC_AMPL_NEUR                   1076
#define IDC_NAME_SOUND                  1076
#define IDC_AMPLP_NEUR                  1077
#define IDC_REPEATS                     1077
#define IDC_AMPLOK_NEUR                 1078
#define IDC_FREQ_SYNTHESIS              1078
#define IDC_AMPL_SYN                    1079
#define IDC_AMP_SYNTHESIS               1079
#define IDC_EQUAL_ADAPT_STEP            1079
#define IDC_AMPLP_SYN                   1080
#define IDC_COE_ADAPT_STEP              1080
#define IDC_HEADER_ALPHA_LIM            1080
#define IDC_AMPLOK_SYN                  1081
#define IDC_ADAPT_STEP_MAX              1081
#define IDC_AMPLM_NEUR                  1082
#define IDC_METH_TRAIN                  1082
#define IDC_WORK                        1083
#define IDC_AMPL_INP                    1084
#define IDC_OPEN_NNW_VOWEL              1086
#define IDC_AMPLP_INP                   1086
#define IDC_OPEN_NNW_CONSONANT          1087
#define IDC_AMPLOK_INP                  1087
#define IDC_SAVE_NNW_VOWEL              1088
#define IDC_SAVE_NNW_CONSONANT          1089
#define IDC_SAVE_AS_NNW_VOWEL           1090
#define IDC_SAVE_AS_NNW_CONSONANT       1091
#define IDC_OPEN_PAR_NNW                1092
#define IDC_SAVE_PAR_NNW                1093
#define IDC_SAVE_AS_PAR_NNW             1094
#define IDC_INIT_NNW                    1095
#define IDC_GET_PAR_FROM_NNW            1096
#define IDC_OPEN_NNW_SPECTR             1097
#define IDC_LIST                        1098
#define IDC_SAVE_NNW_SPECTR             1098
#define IDC_RADIO_GEND_M                1099
#define IDC_SAVE_AS_NNW_SPECTR          1100
#define IDC_OPEN_NNW_COHONEN            1101
#define IDC_SAVE_NNW_COHONEN            1102
#define IDC_RADIO_GEND_W                1103
#define IDC_COMBO_METH                  1104
#define IDC_SAVE_AS_NNW_COHONEN         1104
#define IDC_CHECK_THR_USE               1105
#define IDC_SPIN_REPEATS                1106
#define IDC_CHECK_SHIFTS_USE            1106
#define IDC_RADIO_SHOW_VOWEL            1107
#define IDC_FREQ_CORR                   1107
#define IDC_RADIO_SHOW_CONS             1108
#define IDC_RADIO_AXONS                 1108
#define IDC_RADIO_TRANSFER              1109
#define IDC_RADIO_SHIFTS                1110
#define IDC_RADIO_EXCITATION            1111
#define IDC_FREQ_INI                    1112
#define IDC_FREQ_FIN                    1113
#define IDC_RADIO_TYP_NNW_PEAKS         1114
#define IDC_RADIO_TYP_NNW_SPECTR_TRI    1115
#define IDC_RADIO_TYP_NNW_SPECTR_TRI_ENV 1116
#define IDC_RADIO_TYP_NNW_SPECTR_ALL    1117
#define IDM_DLG_DB                      32777
#define IDM_OPEN_DB                     32779
#define IDM_ADJUST_PAR_PEAKS            32780
#define IDM_NEUR_LOAD_VOWEL             32781
#define IDM_NEUR_LOAD_CONSONANT         32782
#define IDM_NEUR_SAVE_VOWEL             32783
#define IDM_NEUR_SAVE_CONSONANT         32784
#define IDM_NEUR_SAVEAS_VOWEL           32785
#define IDM_NEUR_SAVEAS_CONSONANT       32786
#define IDM_WIN_VISUAL_NNW              32787
#define IDM_ADJ_SOUND_CAPTURE           32788
#define IDM_SAVE_WAV                    32789
#define IDM_WIN_TEXT                    32790
#define IDM_NEUR_LOAD_SPECTR            32791
#define IDM_NEUR_SAVE_SPECTR            32792
#define IDM_NEUR_SAVEAS_SPECTR          32793
#define IDM_HELP                        32794
#define IDM_SET_OUTPUT                  32795
#define IDM_USE_NNW_TWO_SEP             32796
#define IDM_USE_NNW_SINGLE_SPECTR       32797
#define IDM_USE_NNW_COHONEN             32798
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         32799
#define _APS_NEXT_CONTROL_VALUE         1118
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
